version: '3.8'
services:

  postgres:
    container_name: postgres
    image: postgres:15.0-alpine
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - 1111:5432
    env_file:
      - .env

  app:
    container_name: app
    build:
      context: ../
    image: app
    ports:
      - 8001:8000
    env_file:
      - ../.env
    volumes:
      - .env:/usr/src/app/src/.env
    depends_on:
      - postgres


volumes:
  db-data:
    driver: local